spring:
    application:
        name: knowledge-base
    profiles:
        active: dev,private
    data:
        redis:
            database: 0
            timeout: 10s
            password: 123456
            repositories:
                enabled: false
            client-type: jedis
    datasource:
        url: jdbc:mysql://localhost:3306/knowledge_base
        username: root
        password: 179266
        driver-class-name: com.mysql.cj.jdbc.Driver
    neo4j:
        authentication:
            username: neo4j
            password: 12345678
        uri: bolt://localhost:7687
    ai:
        #智朴AI
        zhipuai:
            api-key: xxx
        vectorstore:
            redis:
                initialize-schema: true
                index-name: custom-index
                prefix: custom-prefix
code-assistant:
    project:
        project-path: F:\workspace\code\opensource\dive-into-spring-ai
    arthas:
        url: http://localhost:8563/api
        password: arthas
        username: arthas
server:
    port: 9902
sa-token:
    # token名称 (同时也是cookie名称)
    token-name: token
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
#    timeout: 10
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    active-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: true
    # token风格
    token-style: uuid
    # 是否输出操作日志
    is-log: true
    # 自动续签
    auto-renew: true
oss:
    provider: ali_yun
    # 阿里云oss配置
    ali-yun:
        access-key-id: xx
        access-key-secret: xx
        endpoint: xx
        bucket-name: xx
    # 腾讯云oss配置
    tencent:
        bucket: xx
        region: xx
        secret-id: xx
        secret-key: xx
jimmer:
    dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
    show-sql: true
    pretty-sql: true
    client:
        ts:
            path: /ts.zip
        openapi:
            path: /openapi
            ui-path: /openapi-ui